name: publish Node.js Package
on:
    push:
        tags:
            - v*
jobs:
    Build-and-Publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://npm.pkg.github.com
                  cache: pnpm
            - name: Install Dependencies
              run: pnpm i --frozen-lockfile

            - name: Build & Publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Deploy document
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./docs
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  force_orphan: true
